name: release

on:
  push:
    branches:
      - master

jobs:
  prepare-artifacts:
    name: Prepare Artifacts
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      - name: Create release folder
        run: |
          mkdir -p dist/
          cp test.txt dist/
          cp README.md dist/

      - name: Generate SLSA subject
        id: hash
        working-directory: dist
        run: |
          sha256sum test.txt README.md > test-hashes.sha256
          echo "::set-output name=hashes::$(cat test-hashes.sha256 | base64 -w0)"

      - uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # tag=v3.1.0
        with:
          name: release-assets
          path: dist/*.txt

  provenance:
    needs: 
      - prepare-artifacts
    permissions:
      actions: read # To read the workflow path.
      id-token: write # To sign the provenance.
      contents: write # To add assets to a release.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@bdd89e60dc5387d8f819bebc702987956bcd4913 # tag=v1.2.0
    with:
      base64-subjects: "${{ needs.release.outputs.hashes }}"

  release:
    name: Release
    runs-on: ubuntu-22.04
    needs:
      - prepare-artifacts
      - provenance
    steps:
      - name: Download provenance
        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # tag=v3.0.0
        with:
          name: "${{ needs.provenance.outputs.provenance-name }}"

      - name: Download release assets
        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # tag=v3.0.0
        with:
          name: "release-assets"
      
      - name: list dir
        run: |
          ls -lsaR

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@e1fe1fc00a3729593e87efb2f88475de76d64a24 # tag=v3.1.1
        with:
          extra_plugins: |
            conventional-changelog-conventionalcommits@5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
