name: release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    permissions:
      actions: read # To read the workflow path.
      id-token: write # To sign the provenance.
      contents: write # To add assets to a release.
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
        with:
          fetch-depth: 0

      - name: Generate SLSA subject
        id: hash
        working-directory: dist
        run: |
          sha256sum test.txt README.md > test-hashes.sha256
          echo "::set-output name=hashes::$(cat test-hashes.sha256 | base64 -w0)"

      - uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@bdd89e60dc5387d8f819bebc702987956bcd4913 # tag=v1.2.0
        with:
          base64-subjects: "${{ steps.hash.outputs.hashes }}"
          provenance-name: test-provenance.intoto.jsonl

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@e1fe1fc00a3729593e87efb2f88475de76d64a24 # tag=v3.1.1
        with:
          extra_plugins: |
            conventional-changelog-conventionalcommits@5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
